<img src="https://github.com/milena-seismo/intro-to-eda-and-pandas/blob/main/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Introduction to `pandas`

---

### About
`pandas` is the most popular python package for managing datasets and is used extensively by data scientists.

### Learning Objectives
- Define `pandas` `Series` and `DataFrame` types and their uses.
- Understand the benefit of vectorized dataset operations.
- Read in a dataset with the `pandas` library.


### Notebook Guide
- What is `pandas`, and why are we using it?
- Reading data with `pandas`
- What are vectorized operations and why are they important?
- Conclusions and Takeaways

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

## What is `pandas`?
---

- Not a black-and-white mammal, it stands for **Pan**el **da**ta **s**ystem
- The most universally used data analysis library for Python (for data small enough to fit in-memory)
- Created by Wes McKinney and Open Sourced by AQR Capital Management, LLC 2009
- Implemented in highly optimized Python/Cython
    - Translation: Even though Python is "slow", `pandas` gives us C-like speeds!
- Basically put Python on the map as a data science language!

## Why use `pandas`?

- `pandas` contains all the functionality we need to explore a dataset including:
    - reading in data
    - joining multiple data sets together
    - calculating descriptive statistics
    - visualization
    - and much more!
- also, `pandas`, is **fast** and can handle large data sets (as we will see)

# Getting started with `pandas`
---

One important aspect of `pandas` is that it introduces specific *types* for working with data. When we read in data, we get a `DataFrame`

In [5]:
import pandas as pd
#import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/child-mortality.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/child-mortality.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

We use the `read_csv` method (more on this later) to read in the data. `pandas` supports many different data sources, but CSV files are one of the most common.

We now have a `pandas` object - what is its type?

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
type(12)

int

In [8]:
students = ["Milensa", "Marko", "Ivan"]
type students

SyntaxError: invalid syntax (3135684768.py, line 2)

The entire data set is a `DataFrame`. We can preview it!

In [9]:
df

            entity code  year  child_mortality_rate
0      Afghanistan  AFG  1957                 36.82
1      Afghanistan  AFG  1958                 36.21
2      Afghanistan  AFG  1959                 35.64
3      Afghanistan  AFG  1960                 35.06
4      Afghanistan  AFG  1961                 34.52
...            ...  ...   ...                   ...
17061     Zimbabwe  ZWE  2020                  6.17
17062     Zimbabwe  ZWE  2021                  6.24
17063     Zimbabwe  ZWE  2022                  6.40
17064     Zimbabwe  ZWE  2023                  6.42
17065     Zimbabwe  ZWE  2024                  6.47

[17066 rows x 4 columns]

How many rows and columns is it?

In [10]:
df.head()

        entity code  year  child_mortality_rate
0  Afghanistan  AFG  1957                 36.82
1  Afghanistan  AFG  1958                 36.21
2  Afghanistan  AFG  1959                 35.64
3  Afghanistan  AFG  1960                 35.06
4  Afghanistan  AFG  1961                 34.52

What kind of columns do we have?

In [11]:
df.head(12)

         entity code  year  child_mortality_rate
0   Afghanistan  AFG  1957                 36.82
1   Afghanistan  AFG  1958                 36.21
2   Afghanistan  AFG  1959                 35.64
3   Afghanistan  AFG  1960                 35.06
4   Afghanistan  AFG  1961                 34.52
5   Afghanistan  AFG  1962                 34.02
6   Afghanistan  AFG  1963                 33.50
7   Afghanistan  AFG  1964                 32.97
8   Afghanistan  AFG  1965                 32.45
9   Afghanistan  AFG  1966                 31.95
10  Afghanistan  AFG  1967                 31.48
11  Afghanistan  AFG  1968                 31.00

In [18]:
df.shape

df_rows, df_columns = df.shape
print(f'We have {df_rows} rows, and {df_columns} columns in our Datafeame')

We have 17066 rows, and 4 columns in our Datafeame

In [15]:
df.info

<bound method DataFrame.info of             entity code  year  child_mortality_rate
0      Afghanistan  AFG  1957                 36.82
1      Afghanistan  AFG  1958                 36.21
2      Afghanistan  AFG  1959                 35.64
3      Afghanistan  AFG  1960                 35.06
4      Afghanistan  AFG  1961                 34.52
...            ...  ...   ...                   ...
17061     Zimbabwe  ZWE  2020                  6.17
17062     Zimbabwe  ZWE  2021                  6.24
17063     Zimbabwe  ZWE  2022                  6.40
17064     Zimbabwe  ZWE  2023                  6.42
17065     Zimbabwe  ZWE  2024                  6.47

[17066 rows x 4 columns]>

In [19]:
df.columns

Index(['entity', 'code', 'year', 'child_mortality_rate'], dtype='object')

In [21]:
for col in df.columns:
    print(col.upper())

ENTITY
CODE
YEAR
CHILD_MORTALITY_RATE

In [22]:
df['code']

0        AFG
1        AFG
2        AFG
3        AFG
4        AFG
        ...
17061    ZWE
17062    ZWE
17063    ZWE
17064    ZWE
17065    ZWE
Name: code, Length: 17066, dtype: object

In [25]:
code_col = df['code']
type(code_col)

pandas.core.series.Series

If we need the column names as a list of strings, we can do that

In [12]:
df.tail()

         entity code  year  child_mortality_rate
17061  Zimbabwe  ZWE  2020                  6.17
17062  Zimbabwe  ZWE  2021                  6.24
17063  Zimbabwe  ZWE  2022                  6.40
17064  Zimbabwe  ZWE  2023                  6.42
17065  Zimbabwe  ZWE  2024                  6.47

Rows and columns are all represented as `pandas` `Series` objects. To select a single column, you can use syntax that looks like accessing Python dictionaries:

This is a single column - let's check its type

***Remember:***

* A **`Series`** is a one-dimensional array of values **with an index** (like indices of elements in a list)
* A **`DataFrame`** is a two-dimensional array of values **with both a row and column index**
* It turns out - each column of a `DataFrame` is actually a `Series`!

We can check this row index, which by default is the numbers 0 to length-1:

We can also check what data types `pandas` has inferred for our columns

In `pandas`, "object" means it wasn't obvious what type it should be. Often these are text columns but not always.

We can also get a more complete picture of the data with `.info`

## Vectorized operations
---

Why bother with `DataFrame` and `Series` object when we could use Python lists and dictionaries?

`pandas` uses `numpy` arrays under the hood, which can perform operations **on an entire collection of values** rather than looping through the values individually.

Let's see a basic example.

We'll square the first 100,000 integers: first with a `for` loop, then as a `pandas` `Series` and compare timings.

*(we can use Jupyter's `%%timeit` command to time how long a cell takes to run)*

Option 1: a `for` loop

Option 2: `pandas` `Series`

# Conclusions and Takeaways
---

- `pandas` is the most popular data analysis library in the Python ecosystem
- `pandas` introduces the `Series` and `DataFrame` types to make manipulating data easier
- `pandas` uses vectorized operations to manipulate entire columns at once